# Generated by Django 4.0.5 on 2022-11-14 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='# de Boleta')),
                ('fechaBoleta', models.DateField(verbose_name='Fecha de la Boleta')),
                ('precioTotal', models.IntegerField(verbose_name='Precio Total')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('idEstado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Estado Orden de Pedido')),
                ('nombreEstado', models.CharField(max_length=50, verbose_name='Estado Orden de Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('runCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Run sin puntos')),
                ('dvrunCliente', models.CharField(max_length=1, verbose_name='-')),
                ('sNombreCliente', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('apMaternoCliente', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('fechNacimCliente', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefonoCliente', models.IntegerField(verbose_name='Número Telefónico')),
                ('correoCliente', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
                ('direccionCliente', models.CharField(max_length=150, verbose_name='Dirección')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID del Producto')),
                ('nombreProducto', models.CharField(max_length=60, verbose_name='Nombre del Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del Producto')),
                ('cantStockProd', models.IntegerField(verbose_name='Stock del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='SucursalProveedor',
            fields=[
                ('idSucursalProveedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('idTipoEmpleado', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Tipo de Empleado')),
                ('tipoEmpleado', models.CharField(max_length=50, verbose_name='Tipo Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('idTipoServicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Tipo Servicio')),
                ('descTipoServicio', models.CharField(max_length=50, verbose_name='Descripción del Tipo de Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoCliente',
            fields=[
                ('idVehiculo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Vehiculo')),
                ('patenteVehiculo', models.CharField(max_length=6, unique=True, verbose_name='Patente del Vehículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del Vehículo')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo del Vehículo')),
                ('anio', models.IntegerField(verbose_name='Año del Vehículo')),
                ('runCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfilcliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Servicio')),
                ('nombreServicio', models.CharField(max_length=50, verbose_name='Nombre del Servicio')),
                ('precioServicio', models.IntegerField(verbose_name='Precio del Servicio')),
                ('descrpServicio', models.CharField(max_length=300, verbose_name='Descripción del Servicio')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAtencion',
            fields=[
                ('idCita', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Cita cliente')),
                ('precioCita', models.IntegerField(verbose_name='Precio de la Reserva')),
                ('fechaHoraCita', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('estadoPago', models.BooleanField(default=False, verbose_name='¿Se ha realizado el pago?')),
                ('runCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfilcliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('nombreProveedor', models.CharField(max_length=160, verbose_name='Region')),
                ('correoProveedor', models.CharField(max_length=100, verbose_name='Correo Proveedor')),
                ('telefonoProveedor', models.IntegerField(verbose_name='Precio Producto')),
                ('idSucursalProveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.sucursalproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('runEmpleado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Run sin puntos')),
                ('dvrunEmpleado', models.CharField(max_length=1, verbose_name='-')),
                ('sNombreEmpleado', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('apMaternoEmpleaddo', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('fechNacimEmpleado', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefonoEmpleado', models.IntegerField(verbose_name='Número Telefónico')),
                ('correoEmpleado', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
                ('direccionEmpleado', models.CharField(max_length=150, verbose_name='Dirección')),
                ('fechaInicCont', models.DateField(verbose_name='Fecha del inicio de Contrato')),
                ('fechaTerCont', models.DateField(blank=True, null=True, verbose_name='Fecha del termino de Contrato')),
                ('sueldoEmp', models.IntegerField(verbose_name='Sueldo de Empleado')),
                ('idTipoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoempleado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDePedido',
            fields=[
                ('idOrdenPedido', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID orden de pedido')),
                ('fecha', models.DateField(verbose_name='Fecha de la Orden')),
                ('precioFinal', models.IntegerField(verbose_name='Precio de la Orden de Pedido')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadoorden')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('idDetalleOrden', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Detalle de Orden de Pedido')),
                ('idOrdenPedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ordendepedido', verbose_name='Orden De Pedido')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto', verbose_name='Producto Seleccionado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('idDetalleBoleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID del detalle de boleta')),
                ('idBoleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.boleta')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='idVehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vehiculocliente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='runEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfilempleado'),
        ),
    ]
